wandb_version: 1

batch_size:
  desc: null
  value: 32
lookback:
  desc: null
  value: 8
lookahead:
  desc: null
  value: 4
gamma:
  desc: null
  value: 1.0
num_components:
  desc: null
  value: 16
num_channels:
  desc: null
  value: 16
hidden_size:
  desc: null
  value: 8
train_predict_mode:
  desc: null
  value: direct
data_name:
  desc: null
  value: standard-1.0
data_dir:
  desc: null
  value: ../data/
result_dir:
  desc: null
  value: ../results/
exp_group:
  desc: null
  value: test
exp_name:
  desc: null
  value: baseline
device:
  desc: null
  value: cuda:0
seed:
  desc: null
  value: 0
sample_size:
  desc: null
  value:
  - 8
  - 4
num_workers:
  desc: null
  value: 2
split:
  desc: null
  value:
  - 0.6
  - 0.2
  - 0.2
lr:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 8
run_num:
  desc: null
  value: 1
cycle_to_run:
  desc: null
  value: 10
time_to_run:
  desc: null
  value: 3600
step_length:
  desc: null
  value: 1.0
time_interval:
  desc: null
  value: 1.0
step_num:
  desc: null
  value: 1
warm_up:
  desc: null
  value: 400
snapshot_points:
  desc: null
  value:
  - 24
  - 32
  - 48
  - 60
  - 72
grid_length:
  desc: null
  value: 2.0
obs_range:
  desc: null
  value: 200.0
lane_num:
  desc: null
  value: 4
approach_num:
  desc: null
  value: 4
congestion_threshold:
  desc: null
  value: 200.0
num_enumerations:
  desc: null
  value: 1
num_restarts:
  desc: null
  value: 8
alpha:
  desc: null
  value: 1.0
beta:
  desc: null
  value: 1.0
group_dir:
  desc: null
  value: ../results/test/
model_dir:
  desc: null
  value: ../results/test/baseline/
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1692263402.284988
    t:
      1:
      - 1
      - 53
      - 55
      2:
      - 1
      - 53
      - 55
      3:
      - 1
      - 2
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.15.8
      8:
      - 1
      - 3
      - 5
