batch_size: 32
lookback: 8
lookahead: 4
gamma: 1.000
num_components: 16
num_channels: 16
hidden_size: 8
train_predict_mode: 'direct'

data_dir: "../data/training_data/standard-1.0/"
base_dir: "../results/"
exp_group: "test"
exp_id: "baseline"
# group_dir: "../results/test/"
# id_dir: "../results/test/baseline/"

seed: 0
sample_size: [8,4]
num_workers: 2
split: [0.6,0.2,0.2]
lr: 0.001

# about simulation
cycle_to_run: 10
time_to_run: 3600
step_length: 1.0
time_interval: 1.0
step_num: 1
warm_up: 400

grid_length: 2.0
osb_range: 200.0

# about mpc
num_enumerations: 1
num_restarts: 8
alpha: 1.0
beta: 1.0

